### PR TITLE
Make the client work for API v1

### PR DESCRIPTION
**Pull request by dentarg**
We should probably have some integration tests, right? :)

### CODE REVIEW

**Comment by offtop** [comment]
Critical update, please merge it.

**Comment by jfromaniello** [comment]
Thanks, released as 3.1.2.

Regarding integration tests.. what can we do?

**Comment by dentarg** [comment]
Dedicate an auth0 account for tests, keys can be encrypted in .travis.yml, write tests that actually do stuff with the API. What do you think?

**Comment by dentarg** [comment]
Created #15

**Comment by dentarg** [comment]
> Thanks, released as 3.1.2.

@jfromaniello did you forget to push?

https://github.com/auth0/ruby-auth0/blob/3d2385890b619f1287bdfc33abc348b9e7cd4d51/lib/auth0/version.rb#L3 still says 3.1.1

**Comment by dentarg** [comment]
ping @jfromaniello

**Pull request merged**
