### PR TITLE
Add failed job error details endpoint

### PR DESCRIPTION
**Pull request by makoto-matsumoto**
### Changes

Add endpoint for failed job error details.

### References

https://auth0.com/docs/api/management/v2#!/Jobs/get_errors

### Testing

* [x] This change adds unit test coverage
* [ ] This change adds integration test coverage
* [x] This change has been tested on the latest version of Ruby

### Checklist

* [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
* [x] All existing and new tests complete without errors
* [x] Rubocop passes on all added/modified files
* [ ] All active GitHub checks have passed

### CODE REVIEW

**Comment by joshcanhelp** [comment]
@makoto-matsumoto - Thanks for this as well! We'll get CI running on PRs and get this merged in ASAP, then released this week.

**Comment by joshcanhelp** [comment]
Closing and re-opening to trigger CI

**Comment by joshcanhelp** [comment]
@makoto-matsumoto - OK, this one is ready to go! Just rebase `master` and push and tests should pass 👍

**Comment by makoto-matsumoto** [comment]
@joshcanhelp 

Please confirm this too!

**Comment by joshcanhelp** [comment]
@makoto-matsumoto - Just FYI, the tests are failing because we don't have environmental variables. I'm looking into that this week to see what we can do. I'll make sure this gets merged before the next release. 

Same for #177

**Pull request merged**
