### PR TITLE
Fix Rubocop issues: run > rubocop --auto-correct

### PR DESCRIPTION
**Pull request by joshRpowell**

### CODE REVIEW

**Comment by joshcanhelp** [comment]
Thanks @joshRpowell! I'll review next week and merge 👍 did you have any trouble running that command? I noticed recently that the it was not being run with our `rake` task.

**Comment by joshRpowell** [comment]
No issues running. Would be good to add to the rake task.

I came to this because the RestClient dependency has been at a standstill and is a blocker to a Rails 5.2 bump we’re working on. 

We’re also looking to reduce Memory bloat and have had some success with [httprb](
https://github.com/httprb/http).  This PR was a starting point for swapping out RestClient. 

Nice summary here https://twin.github.io/httprb-is-great/

**Comment by joshcanhelp** [comment]
RE: trouble running ... I ask because it's in our task list but not running. Just have not had a chance to troubleshoot it. 

> I came to this because the RestClient dependency has been at a standstill

Is this on us? I'm happy to take a look at upgrading if so.

> This PR was a starting point for swapping out RestClient.

In this library? I'm definitely open to suggestions here. It's a core part of this SDK, of course, but how the calls are actually made under the hood is mostly irrelevant as long as it works 😄

**Comment by joshcanhelp** [comment]
Turns out I had a `.rubocop.yml` file further up in the project tree that was being picked up so `vendor/**/*` was being ignored. Thanks for prompting me to check that @joshRpowell!

**Comment by joshcanhelp** [comment]
@joshRpowell - Just checking in on this ... looks like this branch picked up a few conflicts. Can you correct and push so I can get this merged? 

Thank you!

**Comment by joshcanhelp** [comment]
No activity, will recreate in another PR

**Pull request closed without merging**
