### PR TITLE
Don't define structs as top-level constants

### LINKED ISSUE #201: Permission Struct Conflicts with Model
Hi I'm using the latest gem version (4.9.0). When upgrading to this new version one of my Permission model fails to load. 

When I open up rails console and start calling methods on it, it fails as it attempts to call methods on this struct instead https://github.com/auth0/ruby-auth0/blob/master/lib/auth0/mixins/permission_struct.rb.

I can run `Object.send(:remove_const, :Permission)` and use my model as expected.

### PR DESCRIPTION
**Pull request by makimoto**
### Changes
Structs defined in lib/auth0/mixins are currently defined as top-level
constants (e.g. `AccessToken`). However, these names are popular and can
conflict with existing classes and break the client application.
Therefore, I'd like to put them as children of `Auth0` module.

### References

Closes #201 

### Testing

Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.

* [ ] This change adds unit test coverage
* [ ] This change adds integration test coverage
* [ ] This change has been tested on the latest version of Ruby

### Checklist

* [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
* [x] All existing and new tests complete without errors
* [x] Rubocop passes on all added/modified files
* [x] All active GitHub checks have passed

### CODE REVIEW

**Comment by joshcanhelp** [comment]
Thanks once again @makimoto!

The problem here, though, is that this would be a breaking change for anyone using these structs, correct? I think this is a positive change but would have to be released in a major (if I understand correctly).

**Comment by makimoto** [comment]
@joshcanhelp Probably, yes.
In this patch, I changed `AccessToken`, `ApiToken`, and `Permission`.
If my understanding is correct, `AccessToken ` and `ApiToken ` are used as return values, so they may not break compatibility unless a client application checks their types. (e.g. `if response.is_a?(AccessToken)`)
However, `Permission` is used as a parameter for some methods (e.g. `add_role_permissions`) so it requires modifications at client applications' end.

**Comment by joshcanhelp** [comment]
@makimoto - The `Permissions` struct can change because that's not been released yet, I'm fine with that. For the others, it's probably best to just add a `# TODO` there and we'll address in a major.

**Comment by pjo336** [comment]
What's the status on this? Anything we could do to move it along? We have some conflicts

**Comment by zinosama** [comment]
Hey @joshcanhelp the Permission struct change is breaking our application. What are the remaining blockers before we can get this merged? Happy to help move this forward 😄 Please let me know.

**Comment by qortex** [comment]
Any chance that could move forward?

**Comment by copiousfreetime** [comment]
I also just encountered this issue and was about to do a pull request for it and saw this. Please do move this forward and release a 5.0 version.

**Comment by qortex** [comment]
> I also just encountered this issue and was about to do a pull request for it and saw this. Please do move this forward and release a 5.0 version.

That would be great, but it seems Auth0 has dropped support for this gem, or at least designated maintainers are no longer taking care of the repo.

@joshcanhelp Can you share Auth0 plans? Should we fork and go on with it ourselves? Thanks for your visibility on this matter.

**Comment by davidpatrick** [comment]
Hey everybody, we apologize for the delay on this.  We have kept putting this off until we had more planned for a 5.0 release.  Considering that we still don't have anything major planned for this SDK, I will move forward with this and https://github.com/auth0/ruby-auth0/issues/171 for a 5.0 release.

**Review by davidpatrick — APPROVED** [review]

**Comment by qortex** [comment]
Great, thanks for your work!

**Pull request merged**
