### PR TITLE
Support optional params for oauth/token endpoint for username-password login

### PR DESCRIPTION
**Pull request by leomao10**
This PR will fix issue #109 by adding support to pass `realm` and `audience` and also include fixes for #107 

I still keep some of the outdated params like `connection` for backward compatibility, but I think it should be removed eventually

### CODE REVIEW

**Comment by joshcanhelp** [comment]
Thanks for the contribution here. I'm going to merge #107 first and then ask you to rebase against that, just FYI.

**Comment by mmaddex** [comment]
I'm curious what backward compatibility keeping `connection`, `id_token`, and `device` provides, given that this method is now hitting an endpoint that doesn't use those params anyway?

**Comment by leomao10** [comment]
Yeah, I guess it is a breaking change anyway? happy to remove those params if you want

**Comment by joshcanhelp** [comment]
@mmaddex - Let's do that in a separate PR. Can't do much about the `id_token` parameter but we can at least deprecate it and remove from the request. 

@leomao10 - For now, let's not expand the scope on this particular PR.

**Comment by joshcanhelp** [comment]
@leomao10 - are you able to rebase and resolve the conflicts here? Also a couple non-blocking questions for you above. 

thank you!

**Comment by leomao10** [comment]
Yup, will do it tonight when I have time, cheers

**Comment by joshcanhelp** [comment]
@leomao10 - Last checkin on this. Are you able to rebase and get this completed? Let me know if not, I can get it into shape in a branch here. Thanks!

**Comment by joshcanhelp** [comment]
We're working on getting the auth endpoints in better shape and will be deprecating this method to clean it up a bit.

**Pull request closed without merging**
