### PR TITLE
Do not lock dependencies to minor version

### PR DESCRIPTION
**Pull request by athix**
Overly restrictive version locks will [cause unnecessary issues for downstream applications](https://github.com/auth0/ruby-auth0/issues/277). All gems should be following semver, such that minor version bumps are completely backwards compatible. By fuzzy locking to the minor version that you need, you both allow upgrading to compatible newer versions, while also ensuring the inclusion of functionality that may have been introduced in a minor version.

### CODE REVIEW

**Comment by athix** [comment]
It appears I can't see why CircleCI is failing without creating an account. Github actions avoids this issue, and provides pretty in-depth CI/CD integrations.

**Comment by cyclotron3k** [comment]
Would be good to take another look at this one. The overly restrictive version locking caused a issue as predicted: https://github.com/auth0/ruby-auth0/issues/277

**Comment by davidpatrick** [comment]
Hey @athix thanks for raising the PR.  The tests are failing locally as well.  It looks to be an issue with rest client 2.1.0

**Review by davidpatrick — APPROVED** [review]

**Comment by athix** [comment]
> Hey @athix thanks for raising the PR. The tests are failing locally as well. It looks to be an issue with rest client 2.1.0

:man_facepalming: It's frustrating that rest-client isn't following semver... Also I took a look and it seems like the library might be unmaintained at the moment, which is a bit concerning. I created an issue to ask about this: https://github.com/rest-client/rest-client/issues/764

Thanks for tracking down what the problem was! :slightly_smiling_face:

**Pull request merged**
