### PR TITLE
Added support for API V1 and API V2

### PR DESCRIPTION
**Pull request by offtop**
Added next actions for client

clients
create_client(name, callbacks="")
update_client(name, callbacks="", client_id=@client_id)
patch_client(name, callbacks="", client_id=@client_id)
connections
connection(connection_name)
delete_connection(connection_name)
create_connection(connection_name, strategy, tenant_domain, domain_aliases=nil)
update_connection(connection_name, tenant_domain, status=true)
logs(options={})
log(id)
user_logs(user_id, page=0, per_page=50)
rules
create_rule(name, script, order=nil,status=true)
update_rule(name, script, order=nil,status=true)
delete_rule(name)
users(search=nil)
user(user_id)
user_devices(user_id)
connection_users(connection_name, search=nil)
enterpriseconnections_users(search_criteria=nil, per_page=500)
socialconnections_users(search_criteria=nil, per_page=500)
client_users(client_id=@client_id)
create_user(email, password, connection_name, request_params={})
send_verification_email(user_id)
change_password_ticket(user_id, new_password, result_url=nil)
verification_ticket(user_id, result_url=nil)
create_public_key(user_id, device, public_key)
update_user_email(user_id, email, verify=true)
update_user_metadata(user_id, metadata={})
update_user_password(user_id, password, verify=true)
update_user_password_using_email(email, password, connection_name, verify=true)
patch_user_metadata(user_id, metadata={})
delete_users
delete_user(user_id)
revoke_user_refresh_token(user_id, refresh_token)
revoke_user_device_public_key(user_id, device)
obtain_access_token
delegation(id_token, target, scope = "open_id")
login(username, password, scope = "openid", id_token=nil, connection_name="Username-Password-Authentication")
signup(email, password, connection_name= "Username-Password-Authentication")
change_password(email, password, connection_name = "Username-Password-Authentication")
token_info(id_token)

added test coverage(unit testing only), added some basic documentation. Updated outdated gems. 
Compatible to ruby v1.9.3 and higher.

Added support for V2,
to enable v2 in options pass parameter: protocol: "v2"
only creating a job is not implemented, cause HTTParty doesn't support multipart messages. 

blacklisted_tokens
add_token_to_blacklist
clients
client
create_client
delete_client
patch_client
get_job
daily_stats
active_users
daily_stats
users
user
create_user
delete_users
delete_user
delete_user_provider
patch_user

### CODE REVIEW

**Comment by jfromaniello** [comment]
This is an awesome pull request, and I am very thankful for taking this library to the next level. 

I'd like to send you a gift, please contact us at supprot@auth0.com with your details if possible.

Regarding the change, thanks again for adding all the methods with tests. Removing the "examples" folder is spot on since it belongs to another project [omniauth0-auth0](https://github.com/auth0/omniauth-auth0).

@mgonto can you take care of moving examples to omniauth0-auth0?

**Comment by offtop** [comment]
I hope one day it will be merged.

**Comment by jfromaniello** [comment]
Thank you very much for your awesome work, and sorry for the long delay.

I've published this as `v3.0.0`.

**Comment by dschenkelman** [comment]
Just in case, the email is support@auth0.com

**Pull request merged**
