### PR TITLE
updated webmock version, updated documentation

### PR DESCRIPTION
**Pull request by offtop**

### CODE REVIEW

**Comment by jfromaniello** [comment]
excuse my ignorance, what do you use to generate the docs? Thanks a lot

**Comment by dentarg** [comment]
Do the docs need to be part of the repo?

**Comment by offtop** [comment]
I used http://yardoc.org/ (just run yard in repo)
@dentearg I don;t really like them here as well, but it seems to be the best way. Any Ideas ?

**Comment by dentarg** [comment]
I think the user can generate the docs or use http://www.rubydoc.info/github/auth0/ruby-auth0

**Comment by dentarg** [comment]
Created #14

**Pull request closed without merging**
