### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by amingilani**

### CODE REVIEW

**Comment by amingilani** [comment]
The current code for the API is incorrect, and not specifying `:api_version => "2"` defaults to `:api_version => "1"` with the error `Auth0::InvalidCredentials: Invalid API v1 client_id and client_secret`

You should've hired me, guys! 😁

**Comment by amingilani** [comment]
This code was still incorrect, sorry. It appears as thought he `:api_version` cannot be a string and has to be an integer.

**Comment by amingilani** [comment]
All fixed now.

**Comment by blueboxjesse** [comment]
Similar to #78. Suggest reviewing and merging both simultaneously.

**Pull request merged**
